name: medical_dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_holo_date_picker:
  intl:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  fl_chart:
  pdf:
  printing:
  path_provider:
  share_plus:
  awesome_snackbar_content:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
